@rootURL = http://localhost:5140

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET{{rootURL}}/api/books/
Accept: application/json

###
GET{{rootURL}}/api/books/2
Accept: application/json

###
POST{{rootURL}}/api/books
Content-Type: application/json

###
PUT{{rootURL}}/api/books/3
Content-Type: application/json

###
DELETE{{rootURL}}/api/books/3